version: '3.4'

services:
  gitlab-runner:
    image: equals215/gitlab-runner:latest
    environment:
      - GITLAB_URL=${GITLAB_URL}
      - GITLAB_RUNNER_TOKEN=${GITLAB_RUNNER_TOKEN}
    networks:
      - net
    privileged: true
    deploy:
      mode: replicated
      replicas: 10
      placement:
        constraints: [node.role == worker]

networks:
  net:
    external:
      name: ci_net
