version: '3.4'

services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_URL}'
        letsencrypt['enable'] = true
        external_url "https://gitlab.example.com"
        letsencrypt['contact_emails'] = ['foo@email.com']
    ports:
      - '80:80'
      - '443:443'
      - '2222:22'
    volumes:
      - /srv/gitlab/config:/etc/gitlab
      - /srv/gitlab/logs:/var/log/gitlab
      - /srv/gitlab/data:/var/opt/gitlab
    networks:
    - ci
    deploy:
      placement:
        constraints: [node.role == manager]
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        order: start-first
        monitor: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

networks:
  ci:
